"""empty message

Revision ID: 3ba9a31fb84c
Revises: 789b06f78289
Create Date: 2025-02-05 21:25:22.661324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba9a31fb84c'
down_revision = '789b06f78289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('person', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vehicle', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('vehicle')
        batch_op.drop_column('person')
        batch_op.drop_column('planet')

    # ### end Alembic commands ###
