"""empty message

Revision ID: 789b06f78289
Revises: 032d9258b299
Create Date: 2025-02-05 20:04:38.738951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '789b06f78289'
down_revision = '032d9258b299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet', sa.String(length=250), nullable=True))
        batch_op.drop_constraint('person_home_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.drop_column('home')
        batch_op.drop_column('home_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('person_home_id_fkey', 'planet', ['home_id'], ['id'])
        batch_op.drop_column('planet')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', postgresql.ENUM('vehicle', 'character', 'planet', name='cat'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
