"""empty message

Revision ID: 802d77ea8c60
Revises: 9c77d5ccc150
Create Date: 2025-02-04 23:52:13.748072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802d77ea8c60'
down_revision = '9c77d5ccc150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)
        batch_op.alter_column('consumables',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('consumables',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
